config/routes.rb
Twitter2::Application.routes.draw do
  get "users/index"
  get "users/show"
  get "tweets/recent"
  get "tweets/update_all_tweets"

  resources :tweets

  resources :comments

  resources :users

  root "welcome#index"
  
  get "welcome/index"
  get "welcome/contact"
  get "welcome/profile"

  
  devise_for :user, :controllers => { :registrations => "registrations" }
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :tweet
	belongs_to :user
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	validates :tweet, :length => { :maximum => 350, :too_long => "350 characters is the maximum allowed tweet" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tweets
  has_many :comments

  include Gravtastic
  gravtastic  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  include TweetsHelper
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    @tweet_id = params["tweet_id"]
    @tweet = Tweet.find(@tweet_id)
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    #@comment.tweet_id = params[:tweet_id]

    @comment.user_id = current_user.id

    #update the number of comment for this tweet
    
      # if a comment is saved set num_comments = 1
      # else num_comments is equal to 0
      # end
      # then under show can you use sum?

   # @current_user_email = current_user.tweet.last

    respond_to do |format|
      if @comment.save
        set_num_comment (comment_params[:tweet_id])
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
        format.js      
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment, :user_id, :tweet_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters, :only => [:create]

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password) }
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  include TweetsHelper

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @comments = @tweet.comments
    @num_comment = @comments.count
  end

  def recent
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  def update_all_tweets

    tweets = Tweet.all

    @response_html = ''

    tweets.each do |tweet|
      set_num_comment (tweet.id)

      tweet_id = tweet.id

      @response_html += "Update tweet <b>#{tweet.id}</b><br>"
    end
    # @response_html = "done!"
  end
  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tweet }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:tweet, :user_id, :num_comment)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!

  def index
  	@users = User.all

  	respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  def show
    # @user = User.find(params[:id])

    # respond_to do |format|
    #  format.html # show.html.erb
    #  format.xml  { render :xml => @user }
  end
end


  

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_filter :authenticate_user!

  def index
    @tweets = Tweet.all
    #@user_tweets = Tweet.find(:all, :conditions => {:user_id => session[:user_id]})
    @user_tweets = current_user.tweets
  end

  def contact
  end

  def profile
  	@tweets = Tweet.all
  	@user_tweets = current_user.tweets
  	# @tweet_comments = tweet.comment
  	@recent_tweets = Tweet.where(user_id: current_user.id)
  	@last10 = Tweet.last(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
	def set_num_comment(tweet_id)
		# need to set a conditional here where the num_comments column is added to if comments are added
		# how do you work with the data here?
		# if a comment is added the num_comments field will add 1
		# else num_comments will have 0
		# sum(:num_comments)
		comments = Comment.where("tweet_id = #{tweet_id}").count

		tweet = Tweet.find(tweet_id)

		tweet.num_comment = comments

		tweet.save

	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <!--<div id="save_message"></div>
  <div id="comment"></div>

  <div class="thriceXXX">
  <div class="thriceXXX">
  <div class="thriceXXX">

  <div id="logged_in"></div>-->


  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  
  <div class="actions">
    <%= f.hidden_field :tweet_id, :value=>@tweet_id%>
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
$('.thriceXXX').append('Repeat user: <%= @comment.user_id %>'); 
$('#save_message').append('NICE WORK!');
$('#comment').append('<%= @comment.comment %>');
$('#logged_in').append('<h3>Thanks for your comment: <%= current_user.email %></h3>');

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1 class=text-center><%= image_tag("comments64.png", :alt => "comment icon") %>   Comments</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Comment</th>
      <th>User</th>
      <th>Tweet</th>
      
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.comment %></td>
        <td><%= comment.user.email %></td>
        <td><%= comment.tweet.tweet %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>

</p>

<p>
  <strong>User:</strong>
  <%= @comment.user.email %>
</p>

<%= @set_num_comment %>




<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <%= link_to 'Tweet', tweets_path, class: 'navbar-brand' %>
      <%= link_to 'Comment', comments_path, class: 'navbar-brand' %>
      <%= link_to 'Users', users_path, class: 'navbar-brand' %>
      </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <p class="navbar-text pull-right">
        <% if user_signed_in? %>

          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Twitter2" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Twitter2" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
          <% if notice %>
            <p class="alert alert-notice"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-error"><%= alert %></p>
          <% end %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="response_message"></div>
  <div id="recent_tweets"></div>


  <div class="field">
    <%= f.label :tweet %><br>
    <%= f.text_field :tweet %>
  </div>
  <!--<div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/create.js.erb
$('#response_message').append('<h1>Thanks for your tweet:</h1> <b><%=@tweet.tweet_text%></b>');
$('#recent_tweets').append('<%=@tweet.last(10)%>');

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1 class=text-center><%= image_tag("tweet64.png", :alt => "tweet icon") %>   Recent Tweets</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Tweet</th>
      <th>User</th>
      <th>Num Comments</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.tweet %></td>
        <td><%= tweet.user.email %></td>
        <td><%= tweet.num_comment %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<!--<%= link_to "Add a comment", new_comment_path(:tweet_id=>@tweet.id) %>-->

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/recent.html.erb
<h2>Listing Recent Tweets:</h2>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @tweet.tweet %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user.email %>
</p>

<p>
  <strong>Comments:</strong>
  <%if @num_comment != 0%>
    <%= link_to "Add a comment", new_comment_path(:tweet_id=>@tweet.id) %>
	<table>
  	  <thead>
    	<tr>
       	  <th></th>
    	</tr>
  	  </thead>

  	<tbody>
    <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.comment %></td>
        </tr>
  	<% end %>
  </tbody>
</table>

<br>

	<%else%>
  	no comments! bummer....<br>
  	<%= link_to "Add a comment", new_comment_path(:tweet_id=>@tweet.id) %>

 <%end%> 


 </p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/update_all_tweets.html.erb
This is updating all tweets. Be Careful!
<br><br>
<%=@response_html%>

app/views/users/index.html.erb
<h1 class=text-center><%= image_tag("profile64.png", :alt => "profile icon") %>   All Users</h1>

<% @users.each do |user| %>

  <li class=text-center><%= mail_to user.email %> | <%= user.first_name %> <%= user.last_name %></li>

<% end %>

app/views/users/show.html.erb
<h1>Current User:</h1>

</p><%= image_tag current_user.gravatar_url %>   <%= current_user.first_name %><%= current_user.last_name %> | <%= current_user.email %></p>
<%= current_user.tweets %>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

<a href="javascript:convertSeconds(1393891200);">convertseconds</a>

app/views/welcome/index.html.erb
<div class="row-fluid">
  <div class="span12 text-center">
    <h1>Welcome to TinyTwitter!<h1>
        <%if user_signed_in? %>
        <p>Hi there <%=current_user.email%>...We're glad you're back. :)</p>
        <p>I know you are ready. <%=link_to "It's time to add some more tweets.", new_tweet_path %></p>
        <p>Don't be afraid to let the world know what you are up to.</p>
        <p>You can check your profile to see your most recent tweets.</p>
        <p>Have fun and tweet away!</p><br>
        <%else%>
        <p>Sign in now:</p>
        <p><%= link_to "Sign In", sign_in %></p>
        <%end%> 
  </div>
          
      <div class="row">
        <div class="col-md-4 text-center">
          <%= link_to image_tag("tweet128.png", :alt => "tweet icon"), '/tweets' %>
          <h3>Tweets</h3>
          <p>tweet  [tweet]</p>
          <p>noun 1. a weak chirping sound, as of a young or small bird. 2. Digital Technology . a very short message posted on the Twitter website: the message may include text, keywords, mentions of specific users, links to websites, and links to images or videos on a website. verb (used without object) 3. to make a weak chirping sound. 4. Digital Technology . to post a message on Twitter: She tweets a lot about movies.verb (used with object) 5. Digital Technology . to post (a message) on Twitter for (people) to read: He tweeted his fans after the event.</p>
        </div>
        <div class="col-md-4 text-center">
          <%= link_to image_tag("comments128.png", :alt => "comment icon"), '/comments' %>
          <h3>Comments</h3>
          <p>com·ment  [kom-ent]</p>
          <p>1. a remark, observation, or criticism: a comment about the weather. 2. gossip; talk: His frequent absences gave rise to comment. 3. a criticism or interpretation, often by implication or suggestion: The play is a comment on modern society. 4. a note in explanation, expansion, or criticism of a passage in a book, article, or the like; annotation. 5. explanatory or critical matter added to a text. </p>
        </div>
        <div class="col-md-4 text-center">
          <%= image_tag("profile128.png", :alt => "profile icon") %>
          <h3>Profiles</h3>
          <p>pro·file  [proh-fahyl]</p>
          <p>1. the outline or contour of the human face, especially the face viewed from one side. 2. a picture or representation of the side view of a head. 3. an outlined view, as of a city or mountain. 4. an outline of an object, as a molding, formed on a vertical plane passed through the object at right angles to one of its principal horizontal dimensions. 5. a drawing or the like representing this.</p>
        </div>
      </div>

 <% @user_tweets.each do |tweet| %>
  <%= tweet.tweet %>
 <%end%>

app/views/welcome/profile.html.erb
<div>
    <div><h4>Recent Tweets...</h4></div>
    <% @last10.each do |tweet| %>
      <table class="table table-bordered table-striped">
        <tr>
          <td><%= tweet.tweet %></td>
        </tr>
        <tr>
          <td><%= tweet.num_comment %> <%= link_to "comments...", tweet %>
          </td>
        </tr>
      </table>
    <% end %>
  </div>

</div>